### ISSUE TITLE
Inquiry about Test code

### ISSUE THREAD

**Issue by Byeong-Hyun** [codyshen0000/ITSRN#2]
Hi, I'm interested in your impressive work, ITSRN.

Could you please tell me your exact PSNR function and shaving factor for the dataset in your paper?  (SCI1K, SCID, SIQAD)

**Comment by codyshen0000** [comment]
Hi, I use the PSNR function from [here](https://github.com/xinntao/EDVR/tree/old_version/codes/metrics), and I have uploaded the code.
